services:
  - type: worker
    name: couchbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot/main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false